version: '3.8'

services:
  vuepress:
    image: node:20
    container_name: vuepress_dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - OTHER_ENV_VAR=value  # 根据需要添加更多环境变量
    command: >
      sh -c "yarn install && yarn dev"  # 安装依赖后启动
    restart: unless-stopped
    networks:
      - vuepress_network

networks:
  vuepress_network:
